import type { Metadata } from 'next';
import '../globals.css';

export const metadata: Metadata = {
  title: 'DigiBook | Login',
  description: 'Generated by Next.js',
  icons: {
    icon: 'https://i.imgur.com/wjGRb4S.png',
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
